import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import MobileNavbar from "@/components/common/MobileNavbar";
import Footer from "@/components/common/Footer";

// Font setup (your setup is perfect, no changes needed here)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- ENHANCED METADATA OBJECT ---
export const metadata = {
  // metadataBase is crucial for resolving absolute paths for social media images.
  // Replace with your actual production domain.
  metadataBase: new URL('https://www.qasaralhaya.netlify.app'), // IMPORTANT: Change this to your domain

  // Best practice for SEO and page titles
  title: {
    default: "Qasar Al Haya | Premium Valet Parking Services",
    template: "%s | Qasar Al Haya Valet Parking",
  },
  description: "Qasar Al Haya offers professional, reliable, and elegant valet parking solutions for private events, corporate functions, hotels, and restaurants.",
  
  // --- All icons are now managed here ---
  icons: {
    icon: [
      { url: '/icons/tab-logo.ico', type: 'image/x-icon', sizes: 'any' },
      { url: '/icons/logo.svg', type: 'image/svg+xml' },
    ],
    apple: '/icons/tab-logo.png', // For Apple devices
    shortcut: '/icons/tab-logo.ico',
  },

  // --- Web App Manifest ---
  manifest: '/site.webmanifest',

  // --- Open Graph (for social media sharing) ---
  openGraph: {
    title: 'Qasar Al Haya | Premium Valet Parking Services',
    description: 'Elevate your guest experience with our professional valet parking solutions.',
    url: 'https://www.qasaralhaya.com', // IMPORTANT: Change this to your domain
    siteName: 'Qasar Al Haya Valet Parking',
    images: [
      {
        url: '/og-image.png', // The image in your /public folder
        width: 1200,
        height: 630,
        alt: 'Qasar Al Haya Valet Parking professional service',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },

  // --- Twitter Card (for sharing on Twitter) ---
  twitter: {
    card: 'summary_large_image',
    title: 'Qasar Al Haya | Premium Valet Parking Services',
    description: 'Seamless, professional valet parking for any occasion.',
    images: ['/og-image.png'],
  },

  // --- Other useful metadata ---
  keywords: ['valet parking', 'private event valet', 'corporate valet', 'hotel valet', 'restaurant valet', 'premium parking service'],
  authors: [{ name: 'Qasar Al Haya' }],
  creator: 'Qasar Al Haya',
};

// --- CLEANED UP ROOT LAYOUT ---
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
        The <head> tag is now automatically generated by Next.js based on the 
        'metadata' object above. No need to add <link> tags here manually.
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <MobileNavbar />
        <main>{children}</main> {/* It's good practice to wrap children in a <main> tag */}
        <Footer />
      </body>
    </html>
  );
}